Repository GU-99/grow-up-pms, pull requests merged in 2024-11, with the labels that each got.

#288 Docs: #287 파일 다운로드 API에 대한 문서화 추가함
  src/main/java/com/growup/pms/file/controller/FileControllerV1.java
  src/main/java/com/growup/pms/file/service/ProfileImageService.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/FileControllerV1DocsTest.java
  src/test/java/com/growup/pms/file/service/ProfileImageServiceTest.java
Labels: 📚 문서화

#291 Config: #289 구글 이메일 발송 시 사용되는 계정 변경함
  src/main/resources/application.yml
Labels: 🐞 버그, 🛠️ 설정, ⚡ 임시 승인

#292 Feat: #290 업로드 시 S3 백엔드 저장소에 저장되는 파일명을 응답으로 반환함
  src/main/java/com/growup/pms/file/controller/FileControllerV1.java
  src/main/java/com/growup/pms/file/controller/dto/response/ProfileImageUpdateResponse.java
  src/main/java/com/growup/pms/file/service/ProfileImageService.java
  src/main/resources/application-prod.yml
Labels: ✨ 기능

#294 Config: #293 크로스 도메인 문제를 해결하기 위해 쿠키에 SameSite에서 None을 전달함
  src/main/java/com/growup/pms/common/config/WebConfig.java
Labels: ✨ 기능, ⚡ 임시 승인

#296 Feat: #295 Secure 속성을 활성화함
  src/main/java/com/growup/pms/common/util/CookieUtil.java
Labels: ✨ 기능, ⚡ 임시 승인

#298 Config: #297 CORS 설정에서 와일드카드 대신 명시적인 값으로 대체함
  src/main/java/com/growup/pms/common/config/SecurityConfig.java
Labels: 🛠️ 설정, ⚡ 임시 승인

#299 Fix: #297 잘못 지정된 프론트엔드 포트를 올바르게 변경함
  src/main/java/com/growup/pms/common/config/SecurityConfig.java
Labels: 🐞 버그, ⚡ 임시 승인

#301 Feat: #300 쿠키의 Domain에 localhost를 지정함
  src/main/java/com/growup/pms/common/util/CookieUtil.java
Labels: ✨ 기능, ⚡ 임시 승인

#303 Docs: #302 사용자 API 문서화 추가
  src/main/java/com/growup/pms/file/service/ProfileImageService.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserLinksUpdateRequest.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
Labels: 📚 문서화, 🛠️ 리팩터링

#305 Feat: #304 팀 생성 로직을 추가함
  src/main/java/com/growup/pms/common/config/WebConfig.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/util/CookieUtil.java
  src/main/java/com/growup/pms/role/repository/RoleRepository.java
  src/main/java/com/growup/pms/team/repository/TeamRepository.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
  src/test/java/com/growup/pms/test/fixture/team/builder/TeamCreateRequestTestBuilder.java
Labels: ✨ 기능, 🧪 테스트

#306 Feat: #209 API 문서 수정
  src/main/java/com/growup/pms/project/controller/dto/request/ProjectCreateRequest.java
  src/main/java/com/growup/pms/project/domain/Project.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusCreateRequest.java
  src/main/java/com/growup/pms/status/controller/dto/response/StatusResponse.java
  src/main/java/com/growup/pms/status/service/dto/StatusCreateCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectUserControllerV1DocsTest.java
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/status/repository/StatusQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/test/fixture/project/builder/ProjectRoleEditRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/builder/StatusCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/builder/StatusResponseTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🛠️ 리팩터링

#308 Config: #307 새로 생성된 AWS 인스턴스에 맞춰 서버 설정을 변경함
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🗄️ DB, ⚙️ 데브옵스, 🛠️ 설정, ⚡ 임시 승인

#310 Fix: #309 더 이상 사용되지 않는 Mailtrap 서비스 관련 코드를 제거함
  src/main/java/com/growup/pms/auth/service/mail/client/SimpleMailClient.java
  src/test/java/com/growup/pms/auth/service/mail/SimpleMailClientTest.java
Labels: 🐞 버그, 🧪 테스트, ⚡ 임시 승인

#312 Config: #311 서버가 새로 배포됨에 따라 오리진을 새로 변경함
  src/main/java/com/growup/pms/common/config/SecurityConfig.java
  src/main/java/com/growup/pms/common/util/CookieUtil.java
Labels: 🛠️ 설정, ⚡ 임시 승인

#316 Config: #315 추가적으로 ECS를 따라 로그를 내보내도록 구성함
  build.gradle
  src/main/resources/logback-spring.xml
  src/main/resources/logback/ecs-file-appender.xml
Labels: 🔗 의존성, 🛠️ 설정, ⚡ 임시 승인

#318 Config: #317 시작 시 DDL을 자동으로 생성하지 않고 검증만 수행함
  src/main/resources/application-prod.yml
Labels: 🛠️ 설정, ⚡ 임시 승인

#320 Fix: #319 CORS 설정에서 PATCH 메서드가 누락된 걸 수정함
  src/main/java/com/growup/pms/common/config/SecurityConfig.java
Labels: 🐞 버그, ⚡ 임시 승인

#322 Feat: #321 팀명 중복을 검사하는 기능을 구현함
  src/main/java/com/growup/pms/team/controller/TeamControllerV1.java
  src/main/java/com/growup/pms/team/controller/dto/response/TeamNameCheckResponse.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TeamControllerV1DocsTest.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#324 Fix: 사용자 정보 수정에 requestBody 어노테이션이 누락되어 추가함
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
Labels: 🐞 버그
