Repository GU-99/grow-up-pms, pull requests merged in 2024-08, with the labels that each got.

#100 Feat: #93 프로젝트 상태 전체 조회 API 문서를 작성함
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/status/controller/dto/response/PageResponse.java
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
Labels: ✨ 기능

#109 Feat: #108 QueryDSL을 위한 기본 환경을 셋업함
  build.gradle
  src/main/java/com/growup/pms/common/config/QueryDslConfig.java
Labels: 🔗 의존성, 🛠️ 설정

#110 Feat:#94 프로젝트 상태 변경 API 문서를 작성함
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusEditRequest.java
  src/main/java/com/growup/pms/status/domain/Status.java
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/main/java/com/growup/pms/status/service/dto/StatusEditDto.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/status/StatusEditRequestTestBuilder.java
Labels: ✨ 기능, 🧪 테스트

#115 Feat: #114 프로젝트 상태 API 경로, 오타 수정 및 상태 변경 API 통합
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusCreateRequest.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusEditRequest.java
  src/main/java/com/growup/pms/status/service/dto/StatusEditDto.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/status/StatusCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/StatusEditRequestTestBuilder.java
Labels: ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#116 Feat: #104 프로젝트 일정 등록 API 문서 작성
  src/main/java/com/growup/pms/role/domain/PermissionType.java
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskCreateRequest.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskDetailResponse.java
  src/main/java/com/growup/pms/task/repository/TaskRepository.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/java/com/growup/pms/task/service/dto/TaskCreateDto.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/task/TaskCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/TaskDetailResponseTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트

#117 Fix: #113 권한 체크 시 사용되는 AOP에서 사용되는 잘못된 포인트컷 표현식을 수정함
  src/main/java/com/growup/pms/common/aop/annotation/ProjectId.java
  src/main/java/com/growup/pms/common/aop/annotation/TeamId.java
  src/main/java/com/growup/pms/common/aop/aspect/AuthorizationAspect.java
  src/main/java/com/growup/pms/common/util/AopUtil.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/common/aop/aspect/AuthorizationAspectTest.java
Labels: 🐞 버그, 🧪 테스트

#118 Feat: #105 프로젝트 일정 조회 API 문서 작성
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskResponse.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/task/TaskResponseTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#123 Feat:#107 프로젝트 일정 삭제 API 문서 작성
  build.gradle
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
Labels: 📚 문서화, ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#127 Refactor: #124 코드리뷰 수정사항 반영
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusCreateRequest.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusEditRequest.java
  src/main/java/com/growup/pms/status/domain/Status.java
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/main/java/com/growup/pms/status/service/dto/StatusCreateCommand.java
  src/main/java/com/growup/pms/status/service/dto/StatusEditCommand.java
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskCreateRequest.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskEditRequest.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/java/com/growup/pms/task/service/dto/TaskCreateCommand.java
  src/main/java/com/growup/pms/task/service/dto/TaskEditCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/status/StatusTestBuilder.java
Labels: 🛠️ 리팩터링

#132 Docs: #131 기존 팀 API에 대한 문서를 새로 갱신함
  .github/workflows/pr_test.yml
  .github/workflows/pr_test_skipped.yml
  src/main/java/com/growup/pms/team/controller/dto/request/TeamCreateRequest.java
  src/main/java/com/growup/pms/team/controller/dto/request/TeamUpdateRequest.java
  src/main/java/com/growup/pms/team/controller/dto/response/TeamResponse.java
  src/main/java/com/growup/pms/team/service/dto/TeamCreateCommand.java
  src/main/resources/data-local.sql
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TeamControllerV1DocsTest.java
  src/test/java/com/growup/pms/team/controller/TeamControllerV1Test.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
  src/test/java/com/growup/pms/test/fixture/team/TeamCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/team/TeamResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/team/TeamUpdateRequestTestBuilder.java
Labels: 📚 문서화

#133 Feat: #111 팀 생성 시 사용자를 검색하는 기능을 구현함
  src/docs/tag-descriptions.yaml
  src/main/java/com/growup/pms/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/growup/pms/auth/domain/SecurityUser.java
  src/main/java/com/growup/pms/auth/service/CustomUserDetailsService.java
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
  src/main/java/com/growup/pms/auth/service/dto/LoginCommand.java
  src/main/java/com/growup/pms/common/validation/FieldMatchValidator.java
  src/main/java/com/growup/pms/common/validation/constraint/FieldMatch.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserCreateRequest.java
  src/main/java/com/growup/pms/user/controller/dto/response/UserSearchResponse.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/repository/CustomizedUserRepository.java
  src/main/java/com/growup/pms/user/repository/CustomizedUserRepositoryImpl.java
  src/main/java/com/growup/pms/user/repository/UserRepository.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/UserCreateCommand.java
  src/main/resources/data-local.sql
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/auth/service/JwtLoginServiceTest.java
  src/test/java/com/growup/pms/common/validation/FieldMatchValidatorTest.java
  src/test/java/com/growup/pms/test/annotation/WithMockSecurityUser.java
  src/test/java/com/growup/pms/test/fixture/auth/LoginRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/SecurityUserTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/UserCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/UserSearchResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/UserTestBuilder.java
  src/test/java/com/growup/pms/test/support/RepositoryTestSupport.java
  src/test/java/com/growup/pms/test/support/WithMockSecurityUserSecurityContextFactory.java
  src/test/java/com/growup/pms/user/repository/CustomizedUserRepositoryImplTest.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#134 Test: #131 기존 인증 API에 대한 문서를 새로 갱신함
  src/main/java/com/growup/pms/auth/controller/LoginControllerV1.java
  src/main/java/com/growup/pms/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
  src/main/java/com/growup/pms/auth/service/JwtTokenService.java
  src/main/java/com/growup/pms/auth/service/RefreshTokenService.java
  src/main/java/com/growup/pms/common/constant/RegexConstants.java
  src/main/java/com/growup/pms/common/security/jwt/JwtAuthTokenFilter.java
  src/main/java/com/growup/pms/common/security/jwt/JwtConstants.java
  src/main/java/com/growup/pms/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/growup/pms/common/security/jwt/dto/TokenDto.java
  src/main/java/com/growup/pms/common/security/jwt/dto/TokenResponse.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserCreateRequest.java
  src/main/resources/application-common.yml
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/auth/service/JwtLoginServiceTest.java
  src/test/java/com/growup/pms/auth/service/JwtTokenServiceTest.java
  src/test/java/com/growup/pms/docs/LoginControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/auth/TokenResponseTestBuilder.java
  src/test/resources/application.yml
Labels: 🧪 테스트

#135 Feat: #125 프로젝트 상태 등록 기능 구현
  src/main/java/com/growup/pms/common/exception/code/ErrorCategory.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/project/domain/Project.java
  src/main/java/com/growup/pms/project/repository/ProjectRepository.java
  src/main/java/com/growup/pms/status/controller/dto/response/StatusResponse.java
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/main/java/com/growup/pms/status/service/dto/StatusCreateCommand.java
  src/test/java/com/growup/pms/status/service/StatusServiceTest.java
Labels: ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#136 Test: #131 기존 팀 초대 API에 대한 문서를 새로 갱신함
  src/main/java/com/growup/pms/common/constant/RegexConstants.java
  src/main/java/com/growup/pms/role/domain/PermissionType.java
  src/main/java/com/growup/pms/team/controller/TeamControllerV1.java
  src/main/java/com/growup/pms/team/controller/dto/request/TeamCreateRequest.java
  src/main/java/com/growup/pms/team/controller/dto/request/TeamUpdateRequest.java
  src/main/java/com/growup/pms/team/domain/Team.java
  src/main/java/com/growup/pms/team/repository/CustomizedTeamUserRepository.java
  src/main/java/com/growup/pms/team/repository/CustomizedTeamUserRepositoryImpl.java
  src/main/java/com/growup/pms/team/repository/TeamUserRepository.java
  src/main/resources/data-local.sql
  src/test/java/com/growup/pms/docs/TeamInvitationControllerV1DocsTest.java
Labels: 🛠️ 리팩터링, 🧪 테스트

#138 Chore: 테스트 서버를 위한 CI 파이프라인을 구성함
  .github/workflows/build_and_deploy.yml
  Dockerfile
  src/main/resources/application-prod.yml
Labels: ⚙️ 데브옵스

#144 Feat: #141 프로젝트 상태 변경 기능 구현
  src/main/java/com/growup/pms/common/exception/code/ErrorCategory.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/project/repository/ProjectRepository.java
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/status/domain/Status.java
  src/main/java/com/growup/pms/status/repository/StatusRepository.java
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/test/java/com/growup/pms/status/service/StatusServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#145 Feat: #142 프로젝트 상태 삭제 기능 구현
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/test/java/com/growup/pms/status/service/StatusServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#146 Feat: #120 사용자가 자신이 가입한 팀 목록을 조회하는 기능을 구현함
  src/main/java/com/growup/pms/common/aop/annotation/CurrentUser.java
  src/main/java/com/growup/pms/team/domain/TeamUser.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepository.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepositoryImpl.java
  src/main/java/com/growup/pms/team/repository/TeamUserRepository.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/response/UserTeamResponse.java
  src/main/java/com/growup/pms/user/repository/CustomizedUserRepositoryImpl.java
  src/main/java/com/growup/pms/user/repository/QueryDslUserRepository.java
  src/main/java/com/growup/pms/user/repository/QueryDslUserRepositoryImpl.java
  src/main/java/com/growup/pms/user/repository/UserRepository.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/resources/data-local.sql
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/role/RoleTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/team/TeamUserTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/UserTeamResponseTestBuilder.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
  src/test/java/com/growup/pms/user/repository/CustomizedUserRepositoryImplTest.java
  src/test/java/com/growup/pms/user/repository/QueryDslUserRepositoryImplTest.java
Labels: ✨ 기능, 🧪 테스트

#148 Refactor: #143 API 변경사항 반영
  qodana.yaml
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskCreateRequest.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskEditRequest.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
Labels: 🛠️ 리팩터링, 🧪 테스트

#154 Feat: #147 프로젝트 일정 등록 기능 구현
  src/main/java/com/growup/pms/common/constant/RegexConstants.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/exceptions/InvalidProjectException.java
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskCreateRequest.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskDetailResponse.java
  src/main/java/com/growup/pms/task/domain/Task.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/java/com/growup/pms/task/service/dto/TaskCreateCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
  src/test/java/com/growup/pms/test/fixture/task/TaskCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/TaskTestBuilder.java
Labels: ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#156 Feat: #149 프로젝트 일정 상태별 전체 조회 기능 구현
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepository.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepositoryImpl.java
  src/main/java/com/growup/pms/task/repository/TaskRepository.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/repository/TaskQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
Labels: ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#157 Feat: #155 물리적 삭제 대신에 논리적으로 삭제하도록 변경함
  src/main/java/com/growup/pms/auth/domain/RefreshToken.java
  src/main/java/com/growup/pms/common/BaseEntity.java
  src/main/java/com/growup/pms/common/BaseTimeEntity.java
  src/main/java/com/growup/pms/invitation/controller/dto/request/TeamInvitationCreateRequest.java
  src/main/java/com/growup/pms/invitation/domian/TeamInvitation.java
  src/main/java/com/growup/pms/invitation/service/TeamInvitationService.java
  src/main/java/com/growup/pms/invitation/service/dto/TeamInvitationCreateCommand.java
  src/main/java/com/growup/pms/project/domain/Project.java
  src/main/java/com/growup/pms/project/domain/ProjectUser.java
  src/main/java/com/growup/pms/role/domain/Permission.java
  src/main/java/com/growup/pms/role/domain/Role.java
  src/main/java/com/growup/pms/role/domain/RolePermission.java
  src/main/java/com/growup/pms/status/domain/Status.java
  src/main/java/com/growup/pms/task/domain/Task.java
  src/main/java/com/growup/pms/team/domain/Team.java
  src/main/java/com/growup/pms/team/domain/TeamUser.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/domain/UserLink.java
  src/test/java/com/growup/pms/docs/TeamInvitationControllerV1DocsTest.java
  src/test/java/com/growup/pms/invitation/controller/TeamInvitationControllerV1Test.java
  src/test/java/com/growup/pms/invitation/service/TeamInvitationServiceTest.java
Labels: ✨ 기능

#161 Feat: #160 팀원을 추방시키는 기능을 구현함
  src/main/java/com/growup/pms/common/exception/code/ErrorCategory.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/role/domain/PermissionType.java
  src/main/java/com/growup/pms/role/domain/TeamRole.java
  src/main/java/com/growup/pms/team/controller/TeamUserControllerV1.java
  src/main/java/com/growup/pms/team/repository/TeamUserRepository.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/main/java/com/growup/pms/team/service/TeamUserService.java
  src/main/resources/data-local.sql
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TeamUserControllerV1Test.java
  src/test/java/com/growup/pms/team/service/TeamUserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#164 Feat: #150 프로젝트 일정 상세 조회 기능 구현
  src/main/java/com/growup/pms/common/exception/code/ErrorCategory.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskDetailResponse.java
  src/main/java/com/growup/pms/task/domain/Task.java
  src/main/java/com/growup/pms/task/repository/TaskRepository.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
Labels: ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#165 Feat: #163 모든 엔티티에 삭제 여부를 추적하는 컬럼을 추가함
  src/main/java/com/growup/pms/common/BaseEntity.java
  src/main/java/com/growup/pms/common/BaseTimeEntity.java
  src/main/java/com/growup/pms/project/domain/Project.java
  src/main/java/com/growup/pms/team/domain/Team.java
  src/main/java/com/growup/pms/user/domain/User.java
Labels: 🛠️ 리팩터링

#166 Feat: #151 프로젝트 일정 변경 기능 구현
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskEditRequest.java
  src/main/java/com/growup/pms/task/domain/Task.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/java/com/growup/pms/task/service/dto/TaskEditCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
  src/test/java/com/growup/pms/test/fixture/task/TaskEditRequestTestBuilder.java
Labels: ✨ 기능, 🧪 테스트

#169 Feat: #167 이메일 인증 코드를 전송하는 기능을 구현함
  build.gradle
  src/main/java/com/growup/pms/auth/domain/RefreshToken.java
  src/main/java/com/growup/pms/auth/service/EmailVerificationService.java
  src/main/java/com/growup/pms/auth/service/RefreshTokenService.java
  src/main/java/com/growup/pms/auth/service/dto/EmailDetails.java
  src/main/java/com/growup/pms/auth/service/mail/MailClient.java
  src/main/java/com/growup/pms/auth/service/mail/MailtrapClient.java
  src/main/java/com/growup/pms/common/config/RedisConfig.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/exceptions/MessageFailureException.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/resources/application-common.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/growup/pms/auth/service/EmailVerificationServiceTest.java
  src/test/java/com/growup/pms/auth/service/RefreshTokenServiceTest.java
  src/test/java/com/growup/pms/auth/service/mail/MailtrapClientTest.java
  src/test/java/com/growup/pms/test/fixture/auth/RefreshTokenTestBuilder.java
  src/test/resources/application.yml
Labels: ✨ 기능, 🔗 의존성, 🧪 테스트

#171 Feat: #57 이메일 인증 코드를 확인하는 기능을 구현함
  src/main/java/com/growup/pms/auth/service/EmailVerificationService.java
  src/main/java/com/growup/pms/common/config/AuditingConfig.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/exceptions/InvalidInputException.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserCreateRequest.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/domain/UserLink.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/UserCreateCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/auth/service/EmailVerificationServiceTest.java
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/user/UserCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#173 Feat: #172 가입된 팀 목록 조회 시 역할명까지 같이 반환되도록 함
  src/main/java/com/growup/pms/user/controller/dto/response/UserTeamResponse.java
  src/main/java/com/growup/pms/user/repository/QueryDslUserRepositoryImpl.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/user/UserTeamResponseTestBuilder.java
  src/test/java/com/growup/pms/user/repository/QueryDslUserRepositoryImplTest.java
Labels: 📚 문서화, ✨ 기능

#174 Feat: #170 일정 목록 조회 API 수정
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepository.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepositoryImpl.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/repository/TaskQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
Labels: 🐞 버그, ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#175 Feat: #162 관리자가 다른 팀원의 역할을 변경할 수 있는 기능을 구현함
  src/main/java/com/growup/pms/GrowUpPmsApplication.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/role/domain/PermissionType.java
  src/main/java/com/growup/pms/team/controller/TeamUserControllerV1.java
  src/main/java/com/growup/pms/team/controller/dto/request/RoleUpdateRequest.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepository.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepositoryImpl.java
  src/main/java/com/growup/pms/team/service/TeamUserService.java
  src/main/resources/application-common.yml
  src/main/resources/data-local.sql
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TeamUserControllerV1Test.java
  src/test/java/com/growup/pms/team/repository/QueryDslTeamUserRepositoryImplTest.java
  src/test/java/com/growup/pms/team/service/TeamUserServiceTest.java
  src/test/java/com/growup/pms/test/fixture/role/RoleTestBuilder.java
  src/test/java/com/growup/pms/user/repository/QueryDslUserRepositoryImplTest.java
Labels: ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#179 Feat: #178 MDC를 통해 로그 메시지에 추가적인 맥락 정보를 포함시킴
  .gitignore
  build.gradle
  src/main/java/com/growup/pms/common/DiscordWebhookAppender.java
  src/main/java/com/growup/pms/common/config/FilterConfig.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/common/filter/MdcFilter.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application-common.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/logback/console-appender.xml
  src/main/resources/logback/discord-appender.xml
  src/main/resources/logback/file-appender.xml
  src/main/resources/spy.properties
Labels: ✨ 기능, 🛠️ 설정, ⚡ 임시 승인

#184 Feat: #183 성능 테스트를 위한 모니터링 환경을 구축함
  build.gradle
  prom/README.md
  prom/docker-compose.yml
  prom/grafana/provisioning/datasources/datasources.yml
  prom/images/grafana-login.png
  prom/prometheus/prometheus.yml
  src/main/resources/application-prod.yml
Labels: 🔗 의존성, 🛠️ 설정, ⚡ 임시 승인

#186 Feat: #183 예외 클래스에서 구체적인 맥락을 포함하도록 개선함
  src/main/java/com/growup/pms/common/exception/code/ErrorCategory.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/dto/ErrorResponse.java
  src/main/java/com/growup/pms/common/exception/exceptions/AuthenticationException.java
  src/main/java/com/growup/pms/common/exception/exceptions/AuthorizationException.java
  src/main/java/com/growup/pms/common/exception/exceptions/BusinessException.java
  src/main/java/com/growup/pms/common/exception/exceptions/DuplicateException.java
  src/main/java/com/growup/pms/common/exception/exceptions/EntityNotFoundException.java
  src/main/java/com/growup/pms/common/exception/exceptions/InternalServerException.java
  src/main/java/com/growup/pms/common/exception/exceptions/InvalidInputException.java
  src/main/java/com/growup/pms/common/exception/exceptions/InvalidProjectException.java
  src/main/java/com/growup/pms/common/exception/exceptions/MessageFailureException.java
  src/main/java/com/growup/pms/common/exception/exceptions/StorageException.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/common/exception/handler/LogFormatter.java
  src/test/java/com/growup/pms/common/exception/handler/GlobalExceptionHandlerTest.java
Labels: 🛠️ 리팩터링, ⚡ 임시 승인

#188 Refactor: #187 여러 개의 예외 클래스를 비즈니스 예외 하나로 통합함
  src/main/java/com/growup/pms/auth/service/JwtTokenService.java
  src/main/java/com/growup/pms/auth/service/mail/MailtrapClient.java
  src/main/java/com/growup/pms/common/aop/aspect/AuthorizationAspect.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/dto/ErrorResponse.java
  src/main/java/com/growup/pms/common/exception/exceptions/AuthenticationException.java
  src/main/java/com/growup/pms/common/exception/exceptions/AuthorizationException.java
  src/main/java/com/growup/pms/common/exception/exceptions/DuplicateException.java
  src/main/java/com/growup/pms/common/exception/exceptions/EntityNotFoundException.java
  src/main/java/com/growup/pms/common/exception/exceptions/InternalServerException.java
  src/main/java/com/growup/pms/common/exception/exceptions/InvalidInputException.java
  src/main/java/com/growup/pms/common/exception/exceptions/InvalidProjectException.java
  src/main/java/com/growup/pms/common/exception/exceptions/MessageFailureException.java
  src/main/java/com/growup/pms/common/exception/exceptions/StorageException.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/common/storage/service/FileSystemStorageService.java
  src/main/java/com/growup/pms/common/util/HashingUtil.java
  src/main/java/com/growup/pms/project/repository/ProjectRepository.java
  src/main/java/com/growup/pms/role/repository/RoleRepository.java
  src/main/java/com/growup/pms/status/repository/StatusRepository.java
  src/main/java/com/growup/pms/task/repository/TaskRepository.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/java/com/growup/pms/team/repository/TeamRepository.java
  src/main/java/com/growup/pms/team/service/TeamInvitationService.java
  src/main/java/com/growup/pms/team/service/TeamUserService.java
  src/main/java/com/growup/pms/user/repository/UserRepository.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/auth/service/JwtTokenServiceTest.java
  src/test/java/com/growup/pms/auth/service/RefreshTokenServiceTest.java
  src/test/java/com/growup/pms/common/aop/aspect/AuthorizationAspectTest.java
  src/test/java/com/growup/pms/status/service/StatusServiceTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
  src/test/java/com/growup/pms/team/service/TeamInvitationServiceTest.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
  src/test/java/com/growup/pms/team/service/TeamUserServiceTest.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: 🛠️ 리팩터링, ⚡ 임시 승인

#191 Feat: #81 파일 다운로드 기능을 구현한다.
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/storage/service/FileSystemStorageService.java
  src/main/java/com/growup/pms/common/storage/service/StorageService.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/domain/UserProfile.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/UserDownloadCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/common/storage/service/FileSystemStorageServiceTest.java
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
Labels: ✨ 기능, 🧪 테스트

#177 Refactor: #176 프로젝트 일정 관련 API 리팩토링
  src/main/java/com/growup/pms/role/domain/PermissionType.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskCreateRequest.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskDetailResponse.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskResponse.java
  src/main/java/com/growup/pms/task/domain/Task.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
  src/test/java/com/growup/pms/test/fixture/task/TaskDetailResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/TaskResponseTestBuilder.java
Labels: ✨ 기능, 🛠️ 리팩터링

#195 Feat: #193 리프레시 토큰을 조기에 만료시키는 로그아웃 기능을 구현함
  build.gradle
  src/main/java/com/growup/pms/auth/controller/LoginControllerV1.java
  src/main/java/com/growup/pms/auth/controller/dto/SecurityUser.java
  src/main/java/com/growup/pms/auth/domain/RefreshToken.java
  src/main/java/com/growup/pms/auth/repository/RefreshTokenRepository.java
  src/main/java/com/growup/pms/auth/service/CustomUserDetailsService.java
  src/main/java/com/growup/pms/auth/service/EmailVerificationService.java
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
  src/main/java/com/growup/pms/auth/service/JwtTokenService.java
  src/main/java/com/growup/pms/auth/service/RedisEmailVerificationService.java
  src/main/java/com/growup/pms/auth/service/RedisRefreshTokenService.java
  src/main/java/com/growup/pms/auth/service/RefreshTokenService.java
  src/main/java/com/growup/pms/auth/service/TransactionHandler.java
  src/main/java/com/growup/pms/auth/service/dto/EmailDetails.java
  src/main/java/com/growup/pms/auth/service/dto/EmailSendCommand.java
  src/main/java/com/growup/pms/auth/service/mail/MailClient.java
  src/main/java/com/growup/pms/auth/service/mail/MailtrapClient.java
  src/main/java/com/growup/pms/common/aop/aspect/AuthorizationAspect.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/growup/pms/team/controller/TeamControllerV1.java
  src/main/java/com/growup/pms/team/controller/TeamInvitationControllerV1.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/auth/service/JwtLoginServiceTest.java
  src/test/java/com/growup/pms/auth/service/JwtTokenServiceTest.java
  src/test/java/com/growup/pms/auth/service/RedisEmailVerificationServiceTest.java
  src/test/java/com/growup/pms/auth/service/RedisRefreshTokenServiceTest.java
  src/test/java/com/growup/pms/auth/service/RefreshTokenServiceTest.java
  src/test/java/com/growup/pms/auth/service/mail/MailtrapClientTest.java
  src/test/java/com/growup/pms/common/aop/aspect/AuthorizationAspectTest.java
  src/test/java/com/growup/pms/docs/LoginControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/auth/RefreshTokenTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/SecurityUserTestBuilder.java
  src/test/java/com/growup/pms/test/support/WithMockSecurityUserSecurityContextFactory.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#196 Test: #192 멱등성을 위해 테스트에 Testcontainers를 통해 프로덕션 환경과 일치시킴
  build.gradle
  src/main/java/com/growup/pms/common/BaseEntity.java
  src/main/java/com/growup/pms/role/domain/Permission.java
  src/main/java/com/growup/pms/role/domain/Role.java
  src/main/java/com/growup/pms/role/domain/RolePermission.java
  src/test/java/com/growup/pms/common/storage/service/FileSystemStorageServiceTest.java
  src/test/java/com/growup/pms/status/repository/StatusQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/team/repository/QueryDslTeamUserRepositoryImplTest.java
  src/test/java/com/growup/pms/test/annotation/ContainerTest.java
  src/test/java/com/growup/pms/test/support/RepositoryTestSupport.java
  src/test/java/com/growup/pms/test/support/TestcontainersInitializer.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: 🔗 의존성, 🧪 테스트

#198 Chore: #197 리뷰어 목록에 진호님을 추가함
  .github/auto_assign_config.yml
Labels: ⚙️ 데브옵스

#201 Test: #199 인증 도메인에 대한 인수 테스트를 추가함
  build.gradle
  src/main/java/com/growup/pms/auth/controller/LoginControllerV1.java
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/dto/ErrorResponse.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/common/util/HashingUtil.java
  src/test/java/com/growup/pms/acceptance/AuthenticationAcceptanceTest.java
  src/test/java/com/growup/pms/test/annotation/DatabaseCleanupTest.java
  src/test/java/com/growup/pms/test/fixture/auth/LoginRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/data/UserTestData.java
  src/test/java/com/growup/pms/test/support/AcceptanceTestSupport.java
  src/test/java/com/growup/pms/test/support/MariaDatabaseCleaner.java
  src/test/java/com/growup/pms/test/support/TestcontainersInitializer.java
  src/test/java/com/growup/pms/test/support/rest/AuthenticationAcceptanceTestAction.java
  src/test/resources/application.yml
Labels: 🐞 버그, 🔗 의존성, 🧪 테스트

#202 Feat: #200 사용자 비밀번호 변경 기능을 구현함
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/request/PasswordUpdateRequest.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/PasswordUpdateCommand.java
  src/test/java/com/growup/pms/test/fixture/user/UserPasswordUpdateTestBuilder.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#203 Feat:#181 프로젝트 등록 기능 구현
  src/main/java/com/growup/pms/project/controller/ProjectControllerV1.java
  src/main/java/com/growup/pms/project/controller/dto/request/ProjectCreateRequest.java
  src/main/java/com/growup/pms/project/controller/dto/request/ProjectUserCreateRequest.java
  src/main/java/com/growup/pms/project/domain/ProjectUser.java
  src/main/java/com/growup/pms/project/service/ProjectService.java
  src/main/java/com/growup/pms/project/service/dto/ProjectCreateCommand.java
  src/main/java/com/growup/pms/project/service/dto/ProjectUserCreateCommand.java
  src/main/java/com/growup/pms/role/domain/PermissionType.java
  src/main/java/com/growup/pms/role/domain/ProjectRole.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/service/ProjectServiceTest.java
  src/test/java/com/growup/pms/test/fixture/project/ProjectCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/project/ProjectTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/project/ProjectUserCreateRequestTestBuilder.java
Labels: ✨ 기능, 🧪 테스트
