Repository GU-99/grow-up-pms, pull requests merged in 2024-07, with the labels that each got.

#58 Feat: #45 리프레시 토큰을 통해 토큰을 재발급하는 API를 추가함
  src/main/java/com/growup/pms/auth/controller/LoginControllerV1.java
  src/main/java/com/growup/pms/auth/domain/RefreshToken.java
  src/main/java/com/growup/pms/auth/domain/SecurityUser.java
  src/main/java/com/growup/pms/auth/dto/AccessTokenResponse.java
  src/main/java/com/growup/pms/auth/dto/LoginRequest.java
  src/main/java/com/growup/pms/auth/repository/RefreshTokenRepository.java
  src/main/java/com/growup/pms/auth/service/CustomUserDetailsService.java
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
  src/main/java/com/growup/pms/auth/service/JwtTokenService.java
  src/main/java/com/growup/pms/auth/service/RefreshTokenService.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/util/HashingUtil.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/domain/UserProfile.java
  src/main/java/com/growup/pms/user/dto/UserCreateRequest.java
  src/main/java/com/growup/pms/user/repository/UserRepository.java
  src/test/java/com/growup/pms/auth/controller/AuthenticationControllerV1Test.java
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/auth/service/JwtLoginServiceTest.java
  src/test/java/com/growup/pms/auth/service/JwtTokenServiceTest.java
  src/test/java/com/growup/pms/auth/service/RefreshTokenServiceTest.java
  src/test/java/com/growup/pms/test/CommonControllerSliceTest.java
  src/test/java/com/growup/pms/test/fixture/auth/LoginRequestFixture.java
  src/test/java/com/growup/pms/test/fixture/auth/RefreshTokenFixture.java
  src/test/java/com/growup/pms/test/fixture/auth/SignInRequestFixture.java
  src/test/java/com/growup/pms/test/fixture/user/UserCreateRequestFixture.java
  src/test/java/com/growup/pms/test/fixture/user/UserFixture.java
Labels: ✨ 기능, 🧪 테스트

#62 Chore: #44 Qodana가 의존성을 캐싱하지 못하는 문제를 수정함
  .github/workflows/pr_test.yml
  .github/workflows/qodana_code_quality.yml
  .github/workflows/update_cache.yml
  .github/workflows/update_gradle_cache.yml
  .gitignore
  build.gradle
  src/main/java/com/growup/pms/common/config/JasyptConfig.java
Labels: ⚙️ 데브옵스

#61 Refactor: #59 재사용성을 위해 불필요한 매개변수를 제거하고 중복 로직을 제거함
  src/main/java/com/growup/pms/auth/controller/LoginControllerV1.java
  src/main/java/com/growup/pms/auth/domain/RefreshToken.java
  src/main/java/com/growup/pms/auth/repository/RefreshTokenRepository.java
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
  src/main/java/com/growup/pms/auth/service/JwtTokenService.java
  src/main/java/com/growup/pms/auth/service/RefreshTokenService.java
  src/main/java/com/growup/pms/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/growup/pms/common/security/jwt/dto/TokenDto.java
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/auth/service/JwtLoginServiceTest.java
  src/test/java/com/growup/pms/auth/service/JwtTokenServiceTest.java
  src/test/java/com/growup/pms/auth/service/RefreshTokenServiceTest.java
  src/test/java/com/growup/pms/test/fixture/auth/TokenDtoFixture.java
  src/test/java/com/growup/pms/test/fixture/common/SecurityUserFixture.java
  src/test/java/com/growup/pms/test/fixture/user/UserFixture.java
Labels: 🛠️ 리팩터링, 🧪 테스트

#67 Chore: #66 리뷰어에 새로 오신 분의 아이디를 추가함
  .github/auto_assign_config.yml
Labels: ⚙️ 데브옵스

#71 Config: #65 Jacoco 리포트에 테스트가 불필요한 클래스들을 제외함
  build.gradle
  gradlew
  lombok.config
Labels: 🧪 테스트, 🛠️ 설정

#63 Feat: #39 팀 CRUD API를 구현함
  build.gradle
  src/main/java/com/growup/pms/common/config/ObjectMapperConfig.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/team/controller/TeamControllerV1.java
  src/main/java/com/growup/pms/team/domain/Team.java
  src/main/java/com/growup/pms/team/dto/TeamCreateRequest.java
  src/main/java/com/growup/pms/team/dto/TeamResponse.java
  src/main/java/com/growup/pms/team/dto/TeamUpdateRequest.java
  src/main/java/com/growup/pms/team/repository/TeamRepository.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/auth/service/JwtLoginServiceTest.java
  src/test/java/com/growup/pms/common/exception/handler/GlobalExceptionHandlerTest.java
  src/test/java/com/growup/pms/team/controller/TeamControllerV1Test.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
  src/test/java/com/growup/pms/test/CommonControllerSliceTest.java
  src/test/java/com/growup/pms/test/annotation/WithMockSecurityUser.java
  src/test/java/com/growup/pms/test/annotation/WithMockSecurityUserSecurityContextFactory.java
  src/test/java/com/growup/pms/test/fixture/team/TeamFixture.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
Labels: ✨ 기능, 🔗 의존성, 🧪 테스트

#73 Config: #68 Spring REST Docs를 위한 초기 환경을 구성함
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/team/controller/TeamControllerV1Test.java
  src/test/java/com/growup/pms/test/AbstractControllerSliceTest.java
  src/test/java/com/growup/pms/test/DefaultControllerSliceTest.java
  src/test/java/com/growup/pms/test/DefaultRestDocsControllerSliceTest.java
  src/test/java/com/growup/pms/test/config/RestDocsConfig.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
Labels: 🔗 의존성, 🧪 테스트, 🛠️ 설정

#72 Feat: #64 응답 바디 대신에 헤더를 통해서 액세스 토큰을 전달하도록 함
  src/main/java/com/growup/pms/auth/controller/LoginControllerV1.java
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
Labels: ✨ 기능

#75 Config: #74 통합 테스트를 위한 공통 클래스 작성
  src/test/java/com/growup/pms/IntegrationTestSupport.java
Labels: 🧪 테스트, 🛠️ 설정

#77 Config: #76 Qodana에서 커스텀 불가능한 코드 커버리지 검사를 제거함
  qodana.yaml
  src/test/java/com/growup/pms/test/IntegrationTestSupport.java
Labels: 🛠️ 설정

#80 Feat: #38 파일 업로드 기능을 구현함
  src/main/java/com/growup/pms/common/exception/code/ErrorCategory.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/exceptions/StorageException.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/common/storage/service/FileSystemStorageService.java
  src/main/java/com/growup/pms/common/storage/service/StorageService.java
  src/main/java/com/growup/pms/common/validation/ImageFileValidator.java
  src/main/java/com/growup/pms/common/validation/constraint/ImageFile.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/domain/UserProfile.java
  src/main/java/com/growup/pms/user/dto/UserUploadRequest.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/resources/application-common.yml
  src/test/java/com/growup/pms/common/storage/service/FileSystemStorageServiceTest.java
  src/test/java/com/growup/pms/common/validation/ImageFileValidatorTest.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
  src/test/resources/application.yml
  src/test/resources/images/testImage.jpg
Labels: ✨ 기능

#79 Feat: #78 인수 테스트를 위한 초기 환경을 구성함
  build.gradle
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/team/controller/TeamControllerV1Test.java
  src/test/java/com/growup/pms/test/DefaultControllerSliceTest.java
  src/test/java/com/growup/pms/test/IntegrationTestSupport.java
  src/test/java/com/growup/pms/test/annotation/AutoServiceMockBeans.java
  src/test/java/com/growup/pms/test/annotation/DatabaseCleanupTest.java
  src/test/java/com/growup/pms/test/annotation/WithMockSecurityUser.java
  src/test/java/com/growup/pms/test/support/AbstractControllerSliceTest.java
  src/test/java/com/growup/pms/test/support/AcceptanceTestSupport.java
  src/test/java/com/growup/pms/test/support/ControllerSliceTestSupport.java
  src/test/java/com/growup/pms/test/support/H2DatabaseCleaner.java
  src/test/java/com/growup/pms/test/support/IntegrationTestSupport.java
  src/test/java/com/growup/pms/test/support/ServiceMockBeanRegistrar.java
  src/test/java/com/growup/pms/test/support/WithMockSecurityUserSecurityContextFactory.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
Labels: 🔗 의존성, 🧪 테스트

#84 Feat: #83 편의성과 가시성을 위해 REST Docs와 Swagger UI를 통합시킴
  .gitignore
  build.gradle
  qodana.yaml
  src/docs/asciidoc/index.adoc
  src/docs/tag-descriptions.yaml
  src/main/resources/application-common.yml
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/team/controller/TeamControllerV1Test.java
  src/test/java/com/growup/pms/test/config/TestSecurityConfig.java
  src/test/java/com/growup/pms/test/support/AbstractControllerSliceTest.java
Labels: 📚 문서화, 🔗 의존성, 🧪 테스트

#86 Chore: #85 테스트 에러 발생 시 발생 위치에 코멘트를 남기도록 함
  .github/workflows/pr_test.yml
Labels: ⚙️ 데브옵스, 🧪 테스트

#88 Hotfix: #87 테이블 수정 사항과 누락된 부분을 엔티티에 반영한다.
  src/main/java/com/growup/pms/status/domain/Status.java
  src/main/java/com/growup/pms/task/domain/Task.java
Labels: 🗄️ DB, 🛠️ 설정

#91 Test: #90 오브젝트 마더에서 테스트 데이터 빌더를 사용하도록 개선함
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/auth/controller/LoginControllerV1Test.java
  src/test/java/com/growup/pms/auth/service/JwtLoginServiceTest.java
  src/test/java/com/growup/pms/auth/service/JwtTokenServiceTest.java
  src/test/java/com/growup/pms/auth/service/RefreshTokenServiceTest.java
  src/test/java/com/growup/pms/common/validation/FieldMatchValidatorTest.java
  src/test/java/com/growup/pms/team/controller/TeamControllerV1Test.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
  src/test/java/com/growup/pms/test/fixture/auth/LoginRequestFixture.java
  src/test/java/com/growup/pms/test/fixture/auth/LoginRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/RefreshTokenFixture.java
  src/test/java/com/growup/pms/test/fixture/auth/RefreshTokenTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/SecurityUserTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/TokenDtoFixture.java
  src/test/java/com/growup/pms/test/fixture/auth/TokenDtoTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/common/SecurityUserFixture.java
  src/test/java/com/growup/pms/test/fixture/team/TeamCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/team/TeamFixture.java
  src/test/java/com/growup/pms/test/fixture/team/TeamTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/team/TeamUpdateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/UserCreateRequestFixture.java
  src/test/java/com/growup/pms/test/fixture/user/UserCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/UserFixture.java
  src/test/java/com/growup/pms/test/fixture/user/UserTestBuilder.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: 🛠️ 리팩터링, 🧪 테스트

#96 Feat: #89 팀원을 초대하는 기능을 구현함
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
  src/main/java/com/growup/pms/auth/service/JwtTokenService.java
  src/main/java/com/growup/pms/auth/service/RefreshTokenService.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCategory.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/invitation/controller/TeamInvitationControllerV1.java
  src/main/java/com/growup/pms/invitation/domian/TeamInvitation.java
  src/main/java/com/growup/pms/invitation/dto/TeamInvitationCreateRequest.java
  src/main/java/com/growup/pms/invitation/repository/TeamInvitationRepository.java
  src/main/java/com/growup/pms/invitation/service/TeamInvitationService.java
  src/main/java/com/growup/pms/team/repository/TeamUserRepository.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/test/java/com/growup/pms/invitation/controller/TeamInvitationControllerV1Test.java
  src/test/java/com/growup/pms/invitation/service/TeamInvitationServiceTest.java
  src/test/java/com/growup/pms/team/controller/TeamControllerV1Test.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
  src/test/java/com/growup/pms/test/fixture/team/TeamInvitationTestBuilder.java
Labels: ✨ 기능, 🧪 테스트

#97 Feat: #92 프로젝트 상태 등록 API 문서를 작성함
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusCreateRequest.java
  src/main/java/com/growup/pms/status/controller/dto/response/StatusResponse.java
  src/main/java/com/growup/pms/status/repository/StatusRepository.java
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/main/java/com/growup/pms/status/service/dto/StatusCreateDto.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/project/ProjectTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/StatusCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/StatusResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/StatusTestBuilder.java
Labels: 📚 문서화, 🧪 테스트
