Repository GU-99/grow-up-pms, pull requests merged in 2024-10, with the labels that each got.

#265 Feat: #248 프로젝트 팀원 추가 기능
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/project/controller/ProjectUserControllerV1.java
  src/main/java/com/growup/pms/project/domain/ProjectUser.java
  src/main/java/com/growup/pms/project/service/ProjectService.java
  src/main/java/com/growup/pms/project/service/ProjectUserService.java
  src/main/java/com/growup/pms/project/service/dto/ProjectUserCreateCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectUserControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/service/ProjectUserServiceTest.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#266 Feat: #249 프로젝트 팀원 제거 및 탈퇴
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/project/controller/ProjectControllerV1.java
  src/main/java/com/growup/pms/project/controller/ProjectUserControllerV1.java
  src/main/java/com/growup/pms/project/repository/ProjectUserRepository.java
  src/main/java/com/growup/pms/project/service/ProjectService.java
  src/main/java/com/growup/pms/project/service/ProjectUserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectControllerV1DocsTest.java
  src/test/java/com/growup/pms/docs/ProjectUserControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/service/ProjectServiceTest.java
  src/test/java/com/growup/pms/project/service/ProjectUserServiceTest.java
  src/test/java/com/growup/pms/test/fixture/project/builder/ProjectUserTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🛠️ 리팩터링, 🧪 테스트, ⚡ 임시 승인

#260 Feat: #233 팀원 목록을 조회하는 기능을 구현함
  src/main/java/com/growup/pms/team/controller/TeamUserControllerV1.java
  src/main/java/com/growup/pms/team/controller/dto/response/TeamUserResponse.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepository.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepositoryImpl.java
  src/main/java/com/growup/pms/team/service/TeamUserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TeamUserControllerV1Test.java
  src/test/java/com/growup/pms/team/service/TeamUserServiceTest.java
  src/test/java/com/growup/pms/test/fixture/team/builder/TeamUserResponseTestBuilder.java
Labels: ✨ 기능, 🧪 테스트

#264 Feat: #261 닉네임 중복 검증 기능을 구현함
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/request/NicknameDuplicationCheckRequest.java
  src/main/java/com/growup/pms/user/repository/UserRepository.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/NicknameDuplicationCheckCommand.java
  src/test/java/com/growup/pms/test/fixture/user/builder/NicknameDuplicationCheckRequestTestBuilder.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#270 Feat: #262 사용자 링크 변경 컨트롤러 레이어 추가함
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
Labels: ✨ 기능

#269 Feat: #250 프로젝트 팀원 권한 변경
  src/main/java/com/growup/pms/project/controller/ProjectUserControllerV1.java
  src/main/java/com/growup/pms/project/controller/dto/request/ProjectRoleEditRequest.java
  src/main/java/com/growup/pms/project/domain/ProjectUser.java
  src/main/java/com/growup/pms/project/service/ProjectUserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectUserControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/service/ProjectUserServiceTest.java
  src/test/java/com/growup/pms/test/fixture/project/builder/ProjectRoleEditRequestTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#271 Feat: #251 프로젝트 팀원 목록 조회 구현
  src/main/java/com/growup/pms/project/controller/ProjectUserControllerV1.java
  src/main/java/com/growup/pms/project/controller/dto/response/ProjectUserResponse.java
  src/main/java/com/growup/pms/project/repository/ProjectUserQueryRepository.java
  src/main/java/com/growup/pms/project/repository/ProjectUserQueryRepositoryImpl.java
  src/main/java/com/growup/pms/project/repository/ProjectUserRepository.java
  src/main/java/com/growup/pms/project/service/ProjectUserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectUserControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/repository/ProjectUserQueryRepositoryTest.java
  src/test/java/com/growup/pms/project/service/ProjectUserServiceTest.java
  src/test/java/com/growup/pms/test/fixture/project/builder/ProjectUserResponseTestBuilder.java
  src/test/resources/schema.sql
Labels: 📚 문서화, ✨ 기능, 🧪 테스트

#273 Feat: #268 일정 수행자 목록 조회 기능 구현
  src/main/java/com/growup/pms/task/controller/TaskUserControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskUserResponse.java
  src/main/java/com/growup/pms/task/repository/TaskUserQueryRepository.java
  src/main/java/com/growup/pms/task/repository/TaskUserQueryRepositoryImpl.java
  src/main/java/com/growup/pms/task/repository/TaskUserRepository.java
  src/main/java/com/growup/pms/task/service/TaskUserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskUserControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/repository/TaskUserQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/service/TaskUserServiceTest.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskUserResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskUserTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트

#274 Feat: #253 프로젝트 일정 수행자 검색 기능 구현
  src/main/java/com/growup/pms/common/constant/SizeConstants.java
  src/main/java/com/growup/pms/project/controller/ProjectUserControllerV1.java
  src/main/java/com/growup/pms/project/controller/dto/response/ProjectUserSearchResponse.java
  src/main/java/com/growup/pms/project/repository/ProjectUserQueryRepository.java
  src/main/java/com/growup/pms/project/repository/ProjectUserQueryRepositoryImpl.java
  src/main/java/com/growup/pms/project/service/ProjectUserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectUserControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/repository/ProjectUserQueryRepositoryTest.java
  src/test/java/com/growup/pms/project/service/ProjectUserServiceTest.java
  src/test/java/com/growup/pms/test/fixture/project/builder/ProjectUserSearchResponseTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트

#277 Feat: #254 프로젝트 일정 수행자 제거 기능 구현
  src/main/java/com/growup/pms/task/controller/TaskUserControllerV1.java
  src/main/java/com/growup/pms/task/repository/TaskUserRepository.java
  src/main/java/com/growup/pms/task/service/TaskUserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskUserControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/service/TaskUserServiceTest.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#280 Feat: #255 프로젝트 일정 파일 업로드 및 다운로드 기능 구현
  src/main/java/com/growup/pms/file/controller/FileControllerV1.java
  src/main/java/com/growup/pms/file/service/TaskAttachmentService.java
  src/main/java/com/growup/pms/task/domain/TaskAttachment.java
  src/main/java/com/growup/pms/task/repository/TaskAttachmentRepository.java
  src/test/java/com/growup/pms/file/service/TaskAttachmentServiceTest.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskAttachmentTestBuilder.java
Labels: ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#284 Feat: #283 소셜로그인 설정 정보 변경
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/resources/application.yml
Labels: ✨ 기능, 🛠️ 설정

#281 Feat: #263 이메일 인증번호 일치여부 검증기능 구현
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/request/VerificationCodeCheckRequest.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/VerificationCodeCheckCommand.java
  src/test/java/com/growup/pms/test/fixture/user/builder/VerificationCodeCheckRequestTestBuilder.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#282 Feat#279 프로젝트 일정 파일 목록 조회 기능 구현
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskAttachmentResponse.java
  src/main/java/com/growup/pms/task/repository/TaskAttachmentQueryRepository.java
  src/main/java/com/growup/pms/task/repository/TaskAttachmentQueryRepositoryImpl.java
  src/main/java/com/growup/pms/task/repository/TaskAttachmentRepository.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/repository/TaskAttachmentQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskAttachmentResponseTestBuilder.java
  src/test/resources/schema.sql
Labels: 📚 문서화, ✨ 기능, 🧪 테스트

#285 Feat: #256 프로젝트 일정 파일 삭제
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/file/controller/FileControllerV1.java
  src/main/java/com/growup/pms/file/service/TaskAttachmentService.java
  src/main/java/com/growup/pms/task/repository/TaskAttachmentRepository.java
  src/test/java/com/growup/pms/file/service/TaskAttachmentServiceTest.java
Labels: ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#286 Fix: #267 프로젝트원 추가 기능 버그 수정
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/project/service/ProjectUserService.java
  src/test/java/com/growup/pms/project/service/ProjectUserServiceTest.java
Labels: 🐞 버그, ⚡ 임시 승인

#276 Refactor: #275 인증 도메인의 중복된 코드를 제거함
  src/main/java/com/growup/pms/auth/controller/LoginControllerV1.java
  src/main/java/com/growup/pms/auth/controller/OauthLoginControllerV1.java
  src/main/java/com/growup/pms/auth/service/OAuth2Service.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/OauthAccessToken.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/OauthProfile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/google/GoogleAccessToken.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/google/GoogleProfile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/KakaoAccessToken.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/KakaoProfile.java
  src/main/java/com/growup/pms/auth/service/mail/EmailVerificationService.java
  src/main/java/com/growup/pms/auth/service/mail/RedisEmailVerificationService.java
  src/main/java/com/growup/pms/auth/service/mail/client/MailClient.java
  src/main/java/com/growup/pms/auth/service/mail/client/MailtrapClient.java
  src/main/java/com/growup/pms/auth/service/oauth/GoogleOauth2Service.java
  src/main/java/com/growup/pms/auth/service/oauth/KakaoOauth2Service.java
  src/main/java/com/growup/pms/auth/service/oauth/Oauth2Service.java
  src/main/java/com/growup/pms/auth/service/oauth/Oauth2ServiceImpl.java
  src/main/java/com/growup/pms/auth/service/oauth/OauthLoginService.java
  src/main/java/com/growup/pms/common/TransactionHandler.java
  src/main/java/com/growup/pms/common/util/CookieUtil.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/test/java/com/growup/pms/auth/service/OauthLoginServiceTest.java
  src/test/java/com/growup/pms/auth/service/RedisEmailVerificationServiceTest.java
  src/test/java/com/growup/pms/auth/service/mail/MailtrapClientTest.java
  src/test/java/com/growup/pms/test/fixture/auth/builder/GoogleProfileTestBuilder.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: 🛠️ 리팩터링
