Repository GU-99/grow-up-pms, pull requests merged in 2024-09, with the labels that each got.

#206 Feat: #204 팀 프로젝트 목록 조회
  src/main/java/com/growup/pms/common/constant/RegexConstants.java
  src/main/java/com/growup/pms/project/controller/ProjectControllerV1.java
  src/main/java/com/growup/pms/project/controller/dto/request/ProjectCreateRequest.java
  src/main/java/com/growup/pms/project/controller/dto/response/ProjectResponse.java
  src/main/java/com/growup/pms/project/repository/ProjectQueryRepository.java
  src/main/java/com/growup/pms/project/repository/ProjectQueryRepositoryImpl.java
  src/main/java/com/growup/pms/project/repository/ProjectRepository.java
  src/main/java/com/growup/pms/project/service/ProjectService.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskCreateRequest.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskEditRequest.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskDetailResponse.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/repository/ProjectQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/project/service/ProjectServiceTest.java
  src/test/java/com/growup/pms/test/fixture/project/ProjectResponseTestBuilder.java
Labels: ✨ 기능, 🧪 테스트

#215 Feat: #213 이메일을 통해 아이디와 비밀번호를 찾는 기능을 구현함
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/common/util/AopUtil.java
  src/main/java/com/growup/pms/common/util/HashingUtil.java
  src/main/java/com/growup/pms/common/util/RandomPasswordGenerator.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/request/RecoverPasswordRequest.java
  src/main/java/com/growup/pms/user/controller/dto/request/RecoverUsernameRequest.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserCreateRequest.java
  src/main/java/com/growup/pms/user/controller/dto/request/VerificationCodeCreateRequest.java
  src/main/java/com/growup/pms/user/controller/dto/response/RecoverPasswordResponse.java
  src/main/java/com/growup/pms/user/controller/dto/response/RecoverUsernameResponse.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/repository/UserRepository.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/RecoverPasswordCommand.java
  src/main/java/com/growup/pms/user/service/dto/RecoverUsernameCommand.java
  src/main/java/com/growup/pms/user/service/dto/UserCreateCommand.java
  src/main/java/com/growup/pms/user/service/dto/VerificationCodeCreateCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/user/RecoverPasswordRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/RecoverUsernameRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/UserCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#218 Feat: #207 엔티티 수정사항 반영
  src/main/java/com/growup/pms/common/constant/RegexConstants.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusCreateRequest.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusEditRequest.java
  src/main/java/com/growup/pms/status/domain/Status.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskCreateRequest.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskEditRequest.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskDetailResponse.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskResponse.java
  src/main/java/com/growup/pms/task/domain/Task.java
  src/main/java/com/growup/pms/task/domain/TaskUser.java
  src/main/java/com/growup/pms/task/domain/TaskUserId.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepositoryImpl.java
  src/main/java/com/growup/pms/task/repository/TaskUserRepository.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/java/com/growup/pms/task/service/dto/TaskCreateCommand.java
  src/main/java/com/growup/pms/task/service/dto/TaskEditCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/repository/TaskQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
  src/test/java/com/growup/pms/test/fixture/status/StatusCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/StatusEditRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/StatusResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/TaskCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/TaskDetailResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/TaskEditRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/TaskResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/TaskTestBuilder.java
Labels: ✨ 기능, 🧪 테스트

#216 Feat: #205 사용자 정보 변경 기능 구현
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserUpdateRequest.java
  src/main/java/com/growup/pms/user/controller/dto/response/UserUpdateResponse.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/domain/UserProfile.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/UserUpdateCommand.java
  src/test/java/com/growup/pms/test/fixture/user/UserUpdateRequestTestBuilder.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#221 Refactor: #219 유저 정보 변경 리팩토링
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserLinksUpdateRequest.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserUpdateRequest.java
  src/main/java/com/growup/pms/user/controller/dto/response/UserUpdateResponse.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/UserLinksUpdateCommand.java
  src/main/java/com/growup/pms/user/service/dto/UserUpdateCommand.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserLinksUpdateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserUpdateRequestTestBuilder.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#223 Fix: #222 토큰을 조기 만료 시 쿠키도 같이 만료하도록 수정함
  src/main/java/com/growup/pms/auth/controller/LoginControllerV1.java
  src/main/java/com/growup/pms/auth/controller/dto/SecurityUser.java
  src/main/java/com/growup/pms/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/growup/pms/auth/service/CustomUserDetailsService.java
  src/main/java/com/growup/pms/auth/service/EmailVerificationService.java
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
  src/main/java/com/growup/pms/auth/service/RedisEmailVerificationService.java
  src/main/java/com/growup/pms/auth/service/RedisRefreshTokenService.java
  src/main/java/com/growup/pms/auth/service/RefreshTokenService.java
  src/main/java/com/growup/pms/auth/service/dto/UserLoginCommand.java
  src/main/java/com/growup/pms/auth/service/mail/MailClient.java
  src/main/java/com/growup/pms/auth/service/mail/MailtrapClient.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/acceptance/AuthenticationAcceptanceTest.java
  src/test/java/com/growup/pms/auth/service/JwtLoginServiceTest.java
  src/test/java/com/growup/pms/auth/service/RedisRefreshTokenServiceTest.java
  src/test/java/com/growup/pms/docs/LoginControllerV1DocsTest.java
Labels: 🐞 버그, 🛠️ 리팩터링, ⚡ 임시 승인

#225 Feat: #224 현재 사용자 정보를 조회하는 기능을 구현함
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/response/UserResponse.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserLinkTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/data/UserTestData.java
  src/test/java/com/growup/pms/user/controller/UserControllerV1Test.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
Labels: ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#228 Feat: #226 팀 목록 조회 API의 응답에 팀장 ID를 같이 내리도록 수정함
  .github/workflows/pr_test.yml
  src/main/java/com/growup/pms/user/controller/dto/response/UserTeamResponse.java
  src/main/java/com/growup/pms/user/repository/QueryDslUserRepositoryImpl.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserTeamResponseTestBuilder.java
  src/test/java/com/growup/pms/user/repository/QueryDslUserRepositoryImplTest.java
Labels: ✨ 기능, ⚡ 임시 승인

#227 Feat: #214 AWS S3에 파일을 업로드 및 다운로드하는 기능을 구현함
  build.gradle
  src/main/java/com/growup/pms/common/config/S3Config.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/exceptions/BusinessException.java
  src/main/java/com/growup/pms/common/storage/service/FileSystemStorageService.java
  src/main/java/com/growup/pms/common/storage/service/StorageService.java
  src/main/java/com/growup/pms/common/validation/ImageFileValidator.java
  src/main/java/com/growup/pms/common/validation/constraint/ImageFile.java
  src/main/java/com/growup/pms/file/service/FileStorageService.java
  src/main/java/com/growup/pms/file/service/S3FileStorageService.java
  src/main/java/com/growup/pms/user/controller/UserControllerV1.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserUploadRequest.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/growup/pms/common/storage/service/FileSystemStorageServiceTest.java
  src/test/java/com/growup/pms/common/validation/ImageFileValidatorTest.java
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/file/service/S3FileStorageServiceTest.java
  src/test/resources/application.yml
Labels: ✨ 기능, 🔗 의존성, 🧪 테스트, ⚡ 임시 승인

#229 Feat: #214 프로필 이미지 업로드 및 다운로드하는 기능을 구현함
  src/main/java/com/growup/pms/common/exception/dto/ErrorResponse.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/growup/pms/common/util/FileNameUtil.java
  src/main/java/com/growup/pms/common/validator/FileValidator.java
  src/main/java/com/growup/pms/common/validator/annotation/File.java
  src/main/java/com/growup/pms/file/controller/FileControllerV1.java
  src/main/java/com/growup/pms/file/domain/FileType.java
  src/main/java/com/growup/pms/file/service/ProfileImageService.java
  src/main/java/com/growup/pms/file/service/S3FileStorageService.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserCreateRequest.java
  src/main/java/com/growup/pms/user/controller/dto/request/UserUpdateRequest.java
  src/main/java/com/growup/pms/user/controller/dto/response/UserResponse.java
  src/main/java/com/growup/pms/user/controller/dto/response/UserUpdateResponse.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/domain/UserProfile.java
  src/main/java/com/growup/pms/user/service/UserService.java
  src/main/java/com/growup/pms/user/service/dto/UserCreateCommand.java
  src/main/java/com/growup/pms/user/service/dto/UserUpdateCommand.java
  src/main/resources/data-local.sql
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/file/service/ProfileImageServiceTest.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserCreateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserUpdateRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/user/data/UserTestData.java
  src/test/java/com/growup/pms/user/service/UserServiceTest.java
  src/test/resources/schema.sql
Labels: ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#232 Feat: #231 현재 사용자 정보 조회 API의 응답에서 사용자 ID, 프로바이더를 같이 내려주도록 수정함
  src/main/java/com/growup/pms/user/controller/dto/response/UserResponse.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/UserControllerV1DocsTest.java
  src/test/java/com/growup/pms/test/fixture/user/builder/UserResponseTestBuilder.java
Labels: ✨ 기능, ⚡ 임시 승인

#230 Feat: #37 카카오와 구글 소셜 로그인 기능을 구현함
  src/main/java/com/growup/pms/auth/controller/OAuthLoginControllerV1.java
  src/main/java/com/growup/pms/auth/service/GoogleOAuth2Service.java
  src/main/java/com/growup/pms/auth/service/KakaoOAuth2Service.java
  src/main/java/com/growup/pms/auth/service/OAuthLoginService.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/google/GoogleAccessToken.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/google/GoogleProfile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/KakaoAccessToken.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/KakaoAccount.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/KakaoProfile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/Profile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/Properties.java
  src/main/java/com/growup/pms/common/config/RestTemplateConfig.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/resources/application-local.yml
  src/test/java/com/growup/pms/auth/service/OAuthLoginServiceTest.java
  src/test/java/com/growup/pms/test/fixture/auth/builder/GoogleAccessTokenTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/builder/GoogleProfileTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/builder/KakaoAccessTokenTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/builder/KakaoProfileTestBuilder.java
  src/test/resources/application.yml
Labels: ✨ 기능, 🧪 테스트

#234 Feat: #208 프로젝트 일정 목록 조회 기능을 수정함
  src/main/java/com/growup/pms/project/controller/dto/response/ProjectResponse.java
  src/main/java/com/growup/pms/status/controller/dto/response/PageResponse.java
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskDetailResponse.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskKanbanResponse.java
  src/main/java/com/growup/pms/task/controller/dto/response/TaskResponse.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepositoryImpl.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/task/repository/TaskQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
  src/test/java/com/growup/pms/test/fixture/status/builder/StatusTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskKanbanResponseTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskResponseTestBuilder.java
  src/test/resources/schema.sql
Labels: ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#237 Config: #236 prod에 OAuth2 설정 추가함
  src/main/resources/application-prod.yml
Labels: 🛠️ 설정

#240 Fix: #239 오류 발생 시에 원인이 되는 예외를 같이 포함하도록 수정함
  src/main/java/com/growup/pms/auth/controller/dto/SecurityUser.java
  src/main/java/com/growup/pms/auth/service/JwtLoginService.java
Labels: 🐞 버그

#243 Feat: #241 임시로 모든 오리진을 허용함
  src/main/java/com/growup/pms/common/config/SecurityConfig.java
Labels: 🛠️ 설정, ⚡ 임시 승인

#244 Config: #241 임시로 클라이언트에서 접근할 수 있는 헤더를 모두 허용함
  src/main/java/com/growup/pms/common/config/SecurityConfig.java
Labels: 🛠️ 설정

#238 Refactor: #235 전의 리뷰 코멘트를 반영해서 소셜 로그인을 리팩토링함
  src/main/java/com/growup/pms/auth/controller/OAuthLoginControllerV1.java
  src/main/java/com/growup/pms/auth/service/GoogleOAuth2Service.java
  src/main/java/com/growup/pms/auth/service/KakaoOAuth2Service.java
  src/main/java/com/growup/pms/auth/service/OAuth2Service.java
  src/main/java/com/growup/pms/auth/service/OAuth2ServiceImpl.java
  src/main/java/com/growup/pms/auth/service/OAuthLoginService.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/OAuthAccessToken.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/OAuthProfile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/google/GoogleAccessToken.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/google/GoogleProfile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/KakaoAccessToken.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/KakaoAccount.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/KakaoProfile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/Profile.java
  src/main/java/com/growup/pms/auth/service/dto/oauth/kakao/Properties.java
  src/main/java/com/growup/pms/common/config/RestTemplateConfig.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/growup/pms/auth/service/OAuthLoginServiceTest.java
  src/test/java/com/growup/pms/test/fixture/auth/builder/GoogleProfileTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/auth/builder/KakaoProfileTestBuilder.java
  src/test/resources/application.yml
Labels: 🛠️ 리팩터링

#246 Config: #245 컨테이너 대신 AWS의 서비스를 사용하도록 설정함
  .github/workflows/pr_test.yml
  src/main/resources/application-prod.yml
Labels: 🗄️ DB, 🛠️ 설정

#247 Feat: #210 프로젝트 일정 및 상태 순서 변경 api
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusEditRequest.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusOrderEditRequest.java
  src/main/java/com/growup/pms/status/controller/dto/request/StatusOrderListEditRequest.java
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/main/java/com/growup/pms/status/service/dto/StatusEditCommand.java
  src/main/java/com/growup/pms/status/service/dto/StatusOrderEditCommand.java
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskEditRequest.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskOrderEditRequest.java
  src/main/java/com/growup/pms/task/controller/dto/request/TaskOrderListEditRequest.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/java/com/growup/pms/task/service/dto/TaskEditCommand.java
  src/main/java/com/growup/pms/task/service/dto/TaskOrderEditCommand.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
  src/test/java/com/growup/pms/docs/TaskControllerV1DocsTest.java
  src/test/java/com/growup/pms/status/service/StatusServiceTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
  src/test/java/com/growup/pms/test/fixture/status/builder/StatusEditRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/builder/StatusOrderEditRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/status/builder/StatusOrderListEditRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskEditRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskOrderEditRequestTestBuilder.java
  src/test/java/com/growup/pms/test/fixture/task/builder/TaskOrderListEditRequestTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트

#257 Feat: #211 프로젝트 설정 변경 기능
  src/main/java/com/growup/pms/project/controller/ProjectControllerV1.java
  src/main/java/com/growup/pms/project/controller/dto/request/ProjectEditRequest.java
  src/main/java/com/growup/pms/project/domain/Project.java
  src/main/java/com/growup/pms/project/service/ProjectService.java
  src/main/java/com/growup/pms/project/service/dto/ProjectEditCommand.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/service/ProjectServiceTest.java
  src/test/java/com/growup/pms/test/fixture/project/builder/ProjectEditRequestTestBuilder.java
Labels: 📚 문서화, ✨ 기능, 🛠️ 리팩터링, 🧪 테스트

#258 Feat: #212 프로젝트 삭제 기능
  src/main/java/com/growup/pms/project/controller/ProjectControllerV1.java
  src/main/java/com/growup/pms/project/service/ProjectService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/ProjectControllerV1DocsTest.java
  src/test/java/com/growup/pms/project/service/ProjectServiceTest.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트
