Repository GU-99/grow-up-pms, pull requests merged in 2024-06, with the labels that each got.

#11 Config: 구글 자바 코드 스타일에서 다소 벗어난 잘못된 주석 규칙을 수정함
  .editorconfig
  styleguide/custom-google-style-4space-indent.xml
Labels: 🛠️ 설정

#16 Config: 체계화를 위해 PR 등록 시 리뷰어와 담당자를 자동으로 할당함
  .github/auto-assign-config.yml
  .github/workflows/auto-assign-action.yml
Labels: ⚙️ 데브옵스

#12 Config: 브랜치를 엄격하게 보호하기 위해 PR 시 테스트가 실패하면 머지가 안되도록 함
  .github/workflows/pr-test-skipped.yml
  .github/workflows/pr-test.yml
Labels: ⚙️ 데브옵스

#20 Config: 컨벤션 규칙 검사를 위해 사용되는 커스텀 Checkstyle 설정 파일 등록
  styleguide/custom_google_checks.xml
Labels: 🛠️ 설정

#21 Chore: #18 `build.gradle` 의존성 정리
  build.gradle
Labels: 🔗 의존성

#22 Feat: #4 슬라이스 테스트 시 범용적으로 사용되는 클래스를 정의
  build.gradle
  src/test/java/com/growup/pms/test/CommonControllerSliceTest.java
  src/test/java/com/growup/pms/test/annotation/AutoServiceMockBeans.java
  src/test/java/com/growup/pms/test/annotation/ServiceMockBeanRegistrar.java
Labels: 🔗 의존성, 🧪 테스트

#24 Config: #17 Jasypt를 사용하여 설정을 암호화함
  .github/workflows/pr-test.yml
  build.gradle
  src/main/java/com/growup/pms/common/config/JasyptConfig.java
  src/test/java/com/growup/pms/common/config/JasyptConfigTest.java
Labels: 🔗 의존성, 🔒 보안

#28 Fix: #27 Qodana가 설정 파일을 제대로 참조하지 못하는 문제를 수정함
  build.gradle
Labels: 🐞 버그, ⚙️ 데브옵스

#30 Config: #29 로컬과 운영 환경에 따른 프로필 파일을 분리함
  build.gradle
  src/main/resources/application-common.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🔗 의존성, 🛠️ 설정

#34 Feat: #33 각 테이블에 대응되는 엔티티를 정의함
  src/main/java/com/growup/pms/common/BaseTimeEntity.java
  src/main/java/com/growup/pms/project/domain/Project.java
  src/main/java/com/growup/pms/role/domain/Role.java
  src/main/java/com/growup/pms/status/domain/Status.java
  src/main/java/com/growup/pms/task/domain/Task.java
  src/main/java/com/growup/pms/team/domain/Team.java
  src/main/java/com/growup/pms/team/domain/TeamUser.java
  src/main/java/com/growup/pms/team/domain/TeamUserId.java
  src/main/java/com/growup/pms/user/domain/Provider.java
  src/main/java/com/growup/pms/user/domain/User.java
  src/main/java/com/growup/pms/user/domain/UserLink.java
  src/main/java/com/growup/pms/user/domain/UserProfile.java
  src/test/java/com/growup/pms/GrowUpPmsApplicationTests.java
Labels: ✨ 기능

#31 Feat: #2 공통 예외처리 기능 개발
  src/main/java/com/growup/pms/common/exception/code/ErrorCategory.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/dto/ErrorResponse.java
  src/main/java/com/growup/pms/common/exception/exceptions/AuthenticationException.java
  src/main/java/com/growup/pms/common/exception/exceptions/AuthorizationException.java
  src/main/java/com/growup/pms/common/exception/exceptions/BusinessException.java
  src/main/java/com/growup/pms/common/exception/exceptions/EntityNotFoundException.java
  src/main/java/com/growup/pms/common/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/growup/pms/common/exception/handler/GlobalExceptionHandlerTest.java
  src/test/java/com/growup/pms/test/annotation/AutoKoreanDisplayName.java
Labels: ✨ 기능

#36 Feat: #1 JWT 인증을 위한 필터를 구성함
  build.gradle
  src/main/java/com/growup/pms/common/config/SecurityConfig.java
  src/main/java/com/growup/pms/common/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/growup/pms/common/security/jwt/JwtAuthTokenFilter.java
  src/main/java/com/growup/pms/common/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/growup/pms/common/security/jwt/JwtTokenProvider.java
  src/main/resources/application-common.yml
  src/test/java/com/growup/pms/common/exception/handler/GlobalExceptionHandlerTest.java
Labels: ✨ 기능, 🔗 의존성, 🔒 보안, 🛠️ 설정

#42 Feat: #41 두 필드가 서로 일치하는지 검증하는 애노테이션을 추가함
  src/main/java/com/growup/pms/common/validation/FieldMatchValidator.java
  src/main/java/com/growup/pms/common/validation/constraint/FieldMatch.java
  src/main/java/com/growup/pms/user/dto/UserCreateRequest.java
  src/test/java/com/growup/pms/common/validation/FieldMatchValidatorTest.java
  src/test/java/com/growup/pms/test/fixture/user/UserCreateRequestFixture.java
Labels: ✨ 기능

#51 Fix: #50 보안 권고사항에 따라서 JWT의 비밀 키를 512비트 이상으로 수정함
  src/main/java/com/growup/pms/common/security/jwt/JwtTokenProvider.java
  src/main/resources/application-common.yml
Labels: 🔒 보안, 🛠️ 설정

#56 Docs: #55 이슈 생성 시 새로 생성된 백엔드 프로젝트를 가리키도록 수정함
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/deployment.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/environment.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/testing.yml
Labels: 📚 문서화

#54 Fix: #53 각각의 PR에서 캐시를 재사용 할 수 있도록 별도의 워크플로우로 분리함
  .github/auto_assign_config.yml
  .github/workflows/auto_assign_action.yml
  .github/workflows/pr_test.yml
  .github/workflows/pr_test_skipped.yml
  .github/workflows/qodana_code_quality.yml
  .github/workflows/update_cache.yml
Labels: ⚙️ 데브옵스
