Repository GU-99/grow-up-pms, pull requests merged in 2024-12, with the labels that each got.

#328 Fix: #327 프로젝트 조회 API의 권한 검사 제거
  src/main/java/com/growup/pms/project/controller/ProjectControllerV1.java
  src/main/java/com/growup/pms/project/controller/ProjectUserControllerV1.java
  src/main/resources/static/docs/openapi3.yaml
Labels: ✨ 기능, ⚡ 임시 승인

#330 Chore: #329 jackson 직렬화 관련 설정 추가
  src/main/resources/application.yml
Labels: 🛠️ 설정, ⚡ 임시 승인

#332 Chore: jackson 직렬화 관련 설정 추가
  src/main/java/com/growup/pms/common/config/ObjectMapperConfig.java
Labels: 🛠️ 설정, ⚡ 임시 승인

#326 Fix: 비밀번호 변경에서 파라미터의 순서를 잘못 지정된 것을 수정함
  src/main/java/com/growup/pms/user/service/UserService.java
Labels: 🐞 버그

#335 Fix: 회원가입 시 이메일 중복체크가 누락된 점을 수정한다
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/user/repository/UserRepository.java
  src/main/java/com/growup/pms/user/service/UserService.java
Labels: 🐞 버그

#339 Fix: #333 권한 관련 문제 해결
  src/main/java/com/growup/pms/role/domain/PermissionType.java
  src/main/resources/data-local.sql
Labels: 🐞 버그, 🗄️ DB

#340 Feat: #338 팀원 검색 기능을 구현함
  src/main/java/com/growup/pms/team/controller/TeamUserControllerV1.java
  src/main/java/com/growup/pms/team/controller/dto/response/TeamUserSearchResponse.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepository.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepositoryImpl.java
  src/main/java/com/growup/pms/team/service/TeamUserService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TeamUserControllerV1Test.java
  src/test/java/com/growup/pms/team/repository/QueryDslTeamUserRepositoryImplTest.java
  src/test/java/com/growup/pms/team/service/TeamUserServiceTest.java
  src/test/java/com/growup/pms/test/fixture/team/builder/TeamUserSearchResponseTestBuilder.java
Labels: ✨ 기능, 🧪 테스트

#342 Feat: 운영서버의 카카오 로그인 콜백 도메인 변경
  src/main/resources/application-prod.yml
Labels: ✨ 기능

#344 Fix: #343 오리진에 누락된 WWW 도메인을 추가함
  src/main/java/com/growup/pms/common/config/SecurityConfig.java
  src/main/java/com/growup/pms/common/config/WebConfig.java
Labels: 🐞 버그, 🛠️ 설정

#350 Chore: #349 임시로 기동 시 스키마 검증을 비활성화함
  src/main/resources/application-prod.yml
Labels: 🐞 버그, 🛠️ 설정

#358 Feat: #345 권한을 이양하는 기능을 구현함
  src/main/java/com/growup/pms/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/common/exception/handler/LogFormatter.java
  src/main/java/com/growup/pms/common/security/jwt/JwtAuthTokenFilter.java
  src/main/java/com/growup/pms/project/domain/Project.java
  src/main/java/com/growup/pms/project/domain/ProjectUser.java
  src/main/java/com/growup/pms/project/repository/ProjectUserRepository.java
  src/main/java/com/growup/pms/team/controller/TeamControllerV1.java
  src/main/java/com/growup/pms/team/controller/dto/request/TeamHeadUpdateRequest.java
  src/main/java/com/growup/pms/team/domain/Team.java
  src/main/java/com/growup/pms/team/repository/TeamUserRepository.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/data-local.sql
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TeamControllerV1DocsTest.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
  src/test/java/com/growup/pms/test/fixture/team/builder/TeamHeadUpdateRequestTestBuilder.java
Labels: ✨ 기능, 🧪 테스트, 🛠️ 설정

#360 Feat: #359 팀원 목록 조회에 가입 대기 여부를 포함시킴
  src/main/java/com/growup/pms/team/controller/dto/response/TeamUserResponse.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepositoryImpl.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/growup/pms/docs/TeamUserControllerV1Test.java
  src/test/java/com/growup/pms/test/fixture/team/builder/TeamUserResponseTestBuilder.java
Labels: ✨ 기능, 🧪 테스트, ⚡ 임시 승인

#362 Chore: #361 테스트 시 생성된 스웨거 파일을 빌드 시에 같이 배포함
  .github/workflows/build_and_deploy.yml
  .github/workflows/pr_test.yml
  .gitignore
Labels: ⚙️ 데브옵스, ⚡ 임시 승인

#363 Chore: #361 API 문서 생성을 위해 빌드 시에 테스트 과정을 포함시킴
  .github/workflows/build_and_deploy.yml
  .github/workflows/pr_test.yml
Labels: ⚙️ 데브옵스, ⚡ 임시 승인

#364 Fix: #361 빌드 시에 JASYPT 비밀번호가 누락된 것을 수정함
  .github/workflows/build_and_deploy.yml
Labels: 🐞 버그, ⚙️ 데브옵스, ⚡ 임시 승인

#346 Feat: #278 일정 삭제 및 상태 삭제 기능 수정
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/status/repository/StatusQueryRepository.java
  src/main/java/com/growup/pms/status/repository/StatusQueryRepositoryImpl.java
  src/main/java/com/growup/pms/status/service/StatusService.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepository.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepositoryImpl.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/test/java/com/growup/pms/docs/StatusControllerV1DocsTest.java
  src/test/java/com/growup/pms/status/repository/StatusQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/status/service/StatusServiceTest.java
  src/test/java/com/growup/pms/task/repository/TaskAttachmentQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/repository/TaskQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#366 Feat: #365 일정 목록 조회 기능 수정
  src/main/java/com/growup/pms/status/repository/StatusRepository.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepository.java
  src/main/java/com/growup/pms/task/repository/TaskQueryRepositoryImpl.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/test/java/com/growup/pms/task/repository/TaskQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
Labels: ✨ 기능, 🛠️ 리팩터링, 🧪 테스트, ⚡ 임시 승인
