Repository GU-99/grow-up-pms, pull requests merged in 2025-01, with the labels that each got.

#368 Fix: #367 일정 생성 시 수행자 null 처리 추가
  src/main/java/com/growup/pms/task/controller/dto/request/TaskCreateRequest.java
  src/main/java/com/growup/pms/task/service/TaskService.java
  src/test/java/com/growup/pms/task/service/TaskServiceTest.java
Labels: 🐞 버그, ⚡ 임시 승인

#370 Feat: #369 프로젝트원 삭제 로직 변경
  src/main/java/com/growup/pms/project/repository/ProjectUserRepository.java
  src/main/java/com/growup/pms/project/service/ProjectUserService.java
  src/test/java/com/growup/pms/project/service/ProjectUserServiceTest.java
Labels: ✨ 기능

#373 Feat: #372 팀장이 팀 탈퇴 시 명확한 에러 메시지를 전송하도록 수정함
  src/main/java/com/growup/pms/common/exception/code/ErrorCode.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#376 Feat: #375 닉네임 부여 로직 변경
  src/main/java/com/growup/pms/auth/service/oauth/OauthLoginService.java
  src/main/java/com/growup/pms/common/util/RandomNicknameGenerator.java
Labels: 🐞 버그, ✨ 기능

#379 Fix: #378 매칭 후보의 혼란을 피하기 위해 기존 마커 애노테이션 제거함
  src/main/java/com/growup/pms/project/controller/ProjectControllerV1.java
Labels: 🐞 버그

#381 Fix: #380 누락된 마커 애노테이션을 추가함
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
Labels: 🐞 버그, ⚡ 임시 승인

#377 Feat: #371 팀 폐쇄 시 프로젝트 및 데이터 제거 기능 로직 추가
  src/main/java/com/growup/pms/project/repository/ProjectQueryRepository.java
  src/main/java/com/growup/pms/project/repository/ProjectQueryRepositoryImpl.java
  src/main/java/com/growup/pms/project/repository/ProjectUserRepository.java
  src/main/java/com/growup/pms/project/service/ProjectService.java
  src/main/java/com/growup/pms/status/repository/StatusRepository.java
  src/main/java/com/growup/pms/task/repository/TaskRepository.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/test/java/com/growup/pms/project/repository/ProjectQueryRepositoryImplTest.java
  src/test/java/com/growup/pms/project/service/ProjectServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#384 Refactor: #383 권한 검사 로직을 더 직관적으로 개선함
  src/main/java/com/growup/pms/common/aop/annotation/ProjectId.java
  src/main/java/com/growup/pms/common/aop/annotation/RequirePermission.java
  src/main/java/com/growup/pms/common/aop/annotation/RequireProjectPermission.java
  src/main/java/com/growup/pms/common/aop/annotation/RequireTeamPermission.java
  src/main/java/com/growup/pms/common/aop/annotation/TeamId.java
  src/main/java/com/growup/pms/common/aop/aspect/AuthorizationAspect.java
  src/main/java/com/growup/pms/common/util/AopUtil.java
  src/main/java/com/growup/pms/common/util/AuthenticationUtil.java
  src/main/java/com/growup/pms/file/controller/FileControllerV1.java
  src/main/java/com/growup/pms/project/controller/ProjectControllerV1.java
  src/main/java/com/growup/pms/project/controller/ProjectUserControllerV1.java
  src/main/java/com/growup/pms/project/service/ProjectService.java
  src/main/java/com/growup/pms/role/domain/BasePermission.java
  src/main/java/com/growup/pms/role/domain/PermissionType.java
  src/main/java/com/growup/pms/role/domain/ProjectPermission.java
  src/main/java/com/growup/pms/role/domain/TeamPermission.java
  src/main/java/com/growup/pms/role/service/PermissionService.java
  src/main/java/com/growup/pms/status/controller/StatusControllerV1.java
  src/main/java/com/growup/pms/task/controller/TaskControllerV1.java
  src/main/java/com/growup/pms/task/controller/TaskUserControllerV1.java
  src/main/java/com/growup/pms/team/controller/TeamControllerV1.java
  src/main/java/com/growup/pms/team/controller/TeamInvitationControllerV1.java
  src/main/java/com/growup/pms/team/controller/TeamUserControllerV1.java
  src/main/java/com/growup/pms/team/repository/TeamRepository.java
  src/main/resources/data-local.sql
  src/test/java/com/growup/pms/common/aop/aspect/AuthorizationAspectTest.java
Labels: 🛠️ 리팩터링, 🧪 테스트

#391 Fix: #390 수행자 제거 시 조건절에 기본 키의 컬럼명이 어긋나 있는 부분을 수정함
  src/main/java/com/growup/pms/task/domain/TaskUser.java
Labels: 🐞 버그, ⚡ 임시 승인

#388 Feat: #374 팀 삭제 기능을 구현함
  src/main/java/com/growup/pms/team/controller/TeamControllerV1.java
  src/main/java/com/growup/pms/team/repository/QueryDslTeamUserRepository.java
  src/main/java/com/growup/pms/team/service/TeamService.java
  src/main/resources/data-local.sql
  src/test/java/com/growup/pms/docs/TeamControllerV1DocsTest.java
  src/test/java/com/growup/pms/team/service/TeamInvitationServiceTest.java
  src/test/java/com/growup/pms/team/service/TeamServiceTest.java
Labels: ✨ 기능, 🧪 테스트

#392 Fix: #390 조건절에 오는 컬럼을 알파벳순으로 배치함
  src/main/java/com/growup/pms/task/domain/TaskUser.java
Labels: 🐞 버그, ⚡ 임시 승인

#395 Fix: #394 권한 검사 시 마커 애노테이션이 누락되어 ID를 찾지 못하는 문제 수정
  qodana.yaml
  src/main/java/com/growup/pms/team/controller/TeamControllerV1.java
Labels: 🐞 버그, 🛠️ 설정, ⚡ 임시 승인
